cookpad/terraform-aws-eks

- examples/cluster/environment.tf
- examples/cluster/environment/main.tf
- examples/cluster/main.tf
- modules/asg_node_group/README.md
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
- modules/cluster/README.md
- modules/cluster/addons.tf
- modules/cluster/addons/aws-node-termination-handler.yaml
- modules/cluster/addons/helm/aws-node-termination-handler.yaml
- modules/cluster/addons/nvidia-device-plugin.yml
- modules/cluster/variables.tf
- test/cluster_test.go
- test/go.mod
- test/go.sum
> Adds GPU support

- UPGRADING.md
- hack/update_1_15.sh
- modules/cluster/main.tf
- modules/cluster/outputs.tf
- modules/cluster/security_groups.tf
- modules/cluster/variables.tf
Fixes #94
See: https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html for background!
> Use Cluster Security Group - By default

- modules/cluster/main.tf
- modules/cluster/variables.tf
> Enable custom tagging of cluster and cloudwatch log group

- examples/cluster/main.tf
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
- modules/cluster/outputs.tf
- modules/cluster/variables.tf
- test/cluster_test.go
- test/common.go
* Tag all the things
* Make a few extra asg things configureable!
> asg_node_group enhancements

- hack/generate_addons.sh
- modules/cluster/addons/helm/prometheus-node-exporter.yaml
- modules/cluster/addons/prometheus-node-exporter.yaml
> Update node exporter in line with documentation

- UPGRADING.md
- examples/cluster/main.tf
- modules/asg_node_group/cloud_config.tpl
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
- modules/cluster/addons.tf
- modules/cluster/addons/coredns.yaml
- modules/cluster/outputs.tf
- modules/cluster/variables.tf
- test/cluster_test.go
* Change some defaults to not deploy metrics components by default
* Pass dns-cluster-ip to coredns and nodes
> Prepare for prometheus

- hack/update_1_15.sh
> Fix bug in upgrade script

- modules/cluster/README.md
> fix var name typo

- docs/service_out_asg_node_group.md
- hack/drain_nodes.sh
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
> Drain node group

- examples/cluster/environment/outputs.tf
- test/cluster_test.go
- test/common.go
- test/go.mod
- test/vpc_test.go
> Fix flaky cleanup

- test/cluster_test.go
Use kube-bench https://github.com/aquasecurity/kube-bench to run
security benchmarks against nodes.
> Add kube-bench

- .github/actions/terratest/entrypoint.sh
- examples/cluster/bottlerocket_node_group/cluster.tf
- examples/cluster/bottlerocket_node_group/main.tf
- hack/test.sh
- modules/asg_node_group/README.md
- modules/asg_node_group/bottlerocket_config.toml.tpl
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
- modules/cluster/addons.tf
- modules/cluster/variables.tf
- modules/iam/node_role.tf
- test/cluster_test.go
> Initial support for bottlerocket

- hack/kubeconfig.sh
- modules/cluster/kubectl/command.sh
- modules/cluster/kubectl/kubeconfig.yaml
- modules/cluster/kubectl/main.tf
> Don't leak kubeconfig file contents into terraform log output

- RELEASING.md
> document release calendar and support

- modules/cluster/addons/prometheus-node-exporter.yaml
To remove dependency on dockerhub
> pull prometheus node-exporter from quay.io

- hack/generate_addons.sh
- modules/cluster/addons/aws-ebs-csi-driver.yaml
- modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/eks_iam_for_sa.yaml
- modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/kustomization.yaml
- modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/resources/crd_snapshotter.yaml
- test/cluster_test.go
> upgrade aws-ebs-csi-controller to 1.0.0

- README.md
This updates the README to include an example that is inline
with the way we would generally expect the module to be used.
Using the root module means that the deployed cluster/vpc/iam setup
is very inflexible, and can't easily be correctly configured etc.
> Update the README to not include the root module in the main example

- .github/workflows/ci.yml
terraform-github-actions deprecated
connects #262
> Switch to setup-terraform github action

- hack/generate_addons.sh
- modules/cluster/addons/cluster-autoscaler.yaml
- modules/cluster/addons/helm/cluster-autoscaler.yaml
> Upgrade autoscaler

- modules/asg_node_group/main.tf
- modules/cluster/addons.tf
- modules/cluster/main.tf
> 1.20 upgrade - control plane, node groups eks addons

- modules/cluster/addons.tf
- modules/cluster/addons/kube-proxy.yaml
> Apply kube-proxy daemonset by manifest not EKS addons

- modules/asg_node_group/main.tf
- modules/cluster/addons.tf
- modules/cluster/addons/kube-proxy.yaml
- modules/cluster/main.tf
> Upgrade to 1.21

- modules/cluster/variables.tf
Move branch for https://github.com/cookpad/terraform-aws-eks/pull/289 to this repository for CI.
context: https://github.com/cookpad/terraform-aws-eks/pull/289#issuecomment-1047619795
> Avoid InvalidParameterException

- examples/cluster/bottlerocket_gpu_node_group/cluster.tf
- examples/cluster/bottlerocket_gpu_node_group/main.tf
- modules/asg_node_group/README.md
- modules/asg_node_group/main.tf
- modules/cluster/addons/helm/nvidia-device-plugin.yaml
- modules/cluster/addons/nvidia-device-plugin.yaml
- test/cluster_test.go
> Add support for GPU enabled bottlerocket nodes

- README.md
This PR updates usage instructions in `README.md` to match the upcoming version, which will be version `1.21`.
> Update README to match the latest version

- modules/asg_node_group/README.md
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
- modules/cluster/addons.tf
- modules/cluster/variables.tf
(note: I'm testing this out on the project outside of Cookpad)
> Support running arm64 instance types on a node group

- modules/asg_node_group/README.md
- modules/asg_node_group/main.tf
- modules/asg_node_group/variables.tf
- modules/cluster/addons.tf
- modules/cluster/variables.tf
resubmission of https://github.com/cookpad/terraform-aws-eks/pull/325 to run test. it seems pull request check doesn't run for head branch on a forked repo
> Support running arm64 instance types on a node group (resubmission for CI)

- UPGRADING.md
Update upgrade notes from 1.22 to 1.23.
> update UPGRADING.md for 1.23

- README.md
- modules/karpenter/README.md
- modules/vpc/README.md
> Update documentation for 1.25 release

- examples/cluster/main.tf
- modules/asg_node_group/versions.tf
- modules/cluster/addons.tf
- modules/cluster/providers.tf
- modules/iam/providers.tf
- modules/vpc/providers.tf
closes https://github.com/cookpad/terraform-aws-eks/issues/356
> Bump aws provider version to 5
