cookpad/terraform-aws-eks

modules/cluster/main.tf

Fixes error when `envelope_encryption_enabled = false`
```
Error: Invalid index
on .terraform/modules/staging-cluster/terraform-aws-eks-1.14.1/modules/cluster/main.tf line 181, in locals:
181:   kms_cmk_arn        = local.create_key ? aws_kms_key.cmk[0].arn : var.kms_cmk_arn
|----------------
| aws_kms_key.cmk is empty tuple
The given key does not identify an element in this collection value.
```

Fix empty tuple key error

---

hack/update_1_15.sh
modules/cluster/outputs.tf
modules/cluster/security_groups.tf

This allows communication to continue between nodes with the legacy sg,
and those using the cluster sg. And means we can remove the legacy node
sg in a later update!

Adds rules to allow traffic between legacy "node" sg and cluster sg

---

modules/cluster/security_groups.tf

The node security group should no longer be used by node groups created
by the 1.15 version of the module. So it should be safe to remove in
1.16

Remove legacy security groups

---

modules/asg_node_group/main.tf

In order to use jinja2 the file  needs to have the `## template: jinja`
comment anyway, without this cloud-config only uses the "basic" renderer
anyway!
https://github.com/canonical/cloud-init/blob/19.3/cloudinit/templater.py#L121
Fixes #102

Don't specify text/jinja2 in cloudconfig parts

---

modules/cluster/cluster_autoscaler_iam.tf

If cluster autoscaler is disabled we can bump into  an error like:
```
Error: Invalid index
on .terraform/modules/eks-cluster-monitoring/terraform-aws-eks-1.15.0-rc4/modules/cluster/cluster_autoscaler_iam.tf line 3, in locals:
3:   cluster_autoscaler_iam_role_arn   = length(var.cluster_autoscaler_iam_role_arn) > 0 || ! var.cluster_autoscaler ? var.cluster_autoscaler_iam_role_arn : aws_iam_role.cluster_autoscaler[0].arn
|----------------
| aws_iam_role.cluster_autoscaler is empty tuple
The given key does not identify an element in this collection value.
```
This should workaround the issue :(

Fix empty tuple error on terraform import

---

modules/cluster/addons/aws-k8s-cni.yaml

The manifest is updated with the following command:
```
curl -s https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.6.1/config/v1.6/aws-k8s-cni.yaml -o modules/cluster/addons/aws-k8s-cni.yaml
```
1.6.1 is the version currently recommended in https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html.
Changelog: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/CHANGELOG.md#v161

Update Amazon VPC CNI plugin to 1.6.1

---

modules/cluster/cluster_autoscaler_iam.tf
modules/cluster/variables.tf

I'd like to add an option to set up [IAM Permissions boundary](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html)
A permissions boundary is an advanced feature for using a managed policy to set the maximum permissions that an identity-based policy can grant to an IAM entity. An entity's permissions boundary allows it to perform only the actions that are allowed by both its identity-based policies and its permissions boundaries.
* Terrafrom aws_iam_role: https://www.terraform.io/docs/providers/aws/d/iam_role.html

Add IAM permissions_boundary variable for cluster_autoscaler IAM role

---

modules/cluster/addons.tf
modules/cluster/variables.tf

It's handy if we can change the configurations of the `critical-addon` node group and `aws_autoscaling_group` based on purposes to use EKS clusters. For example, I don't need huge instances for the `critical-addons` node group when EKS clusters are used for research purposes and want to change the value of `mix_size` and `max_size` for the `asg_node_group` module.
* Add variables for `critical-addon` asg_node_group to the cluster module

Add variables for critical-addons

---

modules/cluster/security_groups.tf

When upgrading a cluster from 1.15 with legacy_security_groups = true
the description change to the legacy control_plane explaining why
this still existed forces the security group to be recreated.
This forces the cluster and a number of other resources to also be
recreated.
This change reverts the description to it's previous value to avoid that
recreation.

Fix upgrade to 1.16 forcing recreation.

---

modules/cluster/addons/kube-proxy.yaml

When kube-proxy is configured with a config file, trying to change
settings with a cmd flag doesn't work.
This pulls in the eks provisioned config-map and changes
`metricsBindAddress` from `127.0.0.1:10249` to `0.0.0.0:10249`

Fix exposing kube-proxy metrics

---

modules/cluster/addons/aws-node-termination-handler.yaml

* Specify `IGNORE_DAEMON_SETS=true` for aws-node-termination-handler 
aws-node-termination-handler behaves as follows when it gets spot interruption and EC2 maintenance events.
* if `--ignore-daemon-sets` is specified and the value is `true`, aws-node-termination-handler ignores DaemonSet and drains other pods (`kubectl drain --ignore-daemon-sets`)
* if `--ignore-daemon-sets` is specified and the value is `false`, aws-node-termination-handler drains all pods. If there are DaemonSets, the drain for all pods does not happen (`kubectl drain`)
* if `--ignore-daemon-sets` is not specified and `IGNORE_DAEMON_SETS` is not passed, aws-node-termination-handler ignores DaemonSet and drains other pods (`kubectl drain --ignore-daemon-sets`)
* if `--ignore-daemon-sets` is not specified and …

Specify true for IGNORE_DAEMON_SETS in aws-node-termination-handler manifest

---

modules/cluster/addons/helm/aws-node-termination-handler.yaml

This option was already changed in the generated manifest in #126 this
change just avoids undoing that change when we run `hack/generate_addons.sh`
FYI: @takanabe

Adds the ignoreDaemonSets value to the helm config for aws-node-termination-handler

---

.github/actions/terratest/entrypoint.sh
examples/cluster/main.tf
hack/generate_addons.sh
hack/test.sh
modules/cluster/README.md
modules/cluster/addons.tf
modules/cluster/addons/aws-alb-ingress-controller.yaml
modules/cluster/addons/kustomize/overlays/aws-alb-ingress-controller/deployment_args.yaml
modules/cluster/addons/kustomize/overlays/aws-alb-ingress-controller/eks_iam_for_sa.yaml
modules/cluster/addons/kustomize/overlays/aws-alb-ingress-controller/kustomization.yaml
modules/cluster/aws_alb_ingress_controller_iam.tf
modules/cluster/variables.tf
test/cluster_test.go

This PR introduces support for provisioning the ALB ingress controller.
For now the default is to not provision this component, based on the discussions in #87 as some cluster admins might prefer to use another implementation.
It can be enabled by setting `aws_alb_ingress_controller = true` on the Cluster module.
Fixes #87

ALB Ingress Controller

---

modules/asg_node_group/main.tf
modules/asg_node_group/variables.tf
modules/cluster/outputs.tf

This will assist cluster autoscaler in choosing the right ASG to scale
up when zone is important, e.g. when handling EBS volumes or zone
(anti)affinity!

Adds node region and zone topology labels to autoscaler template

---

modules/cluster/addons/coredns.yaml

* https://docs.aws.amazon.com/eks/latest/userguide/coredns.html
* https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-08-12/dns.yaml
Reverse lookups were not working with the previous configuration.

Update coredns manifests

---

modules/cluster/addons/coredns.yaml

The upstream option was previously ignored, but has been removed in
version 1.7.0
Also sets healthcheck lameduck option inline with kubernetes defaults

Update coredns configuration

---

.github/actions/terratest/entrypoint.sh
.github/workflows/ci.yml
examples/cluster/environment.tf
examples/cluster/environment/backend.tf
examples/cluster/environment/main.tf
examples/cluster/environment/variables.tf
hack/assume_role.sh
hack/cleanup.sh
hack/kubeconfig.sh
hack/test.sh
test/cluster_test.go
test/common.go

We are seeing a lot of test failures relating to cleanup of the network
components.
This change means that we will pre-provision the VPC used in the tests
and re-use it for each test run.

Use pre-provisioned environment

---

.github/workflows/ci.yml
UPGRADING.md
modules/cluster/outputs.tf
outputs.tf

rename oidc outputs

---

test/cluster_test.go

The format of kube-bench output changed from 0.4.0 to 0.5.0.
DriveBy: Fix json tag names - this might result in *different* failures
as everything might not get the default 0 value.

Update tests for new kube-bench format

---

.github/workflows/ci.yml

They've renamed their `master` to `main`. Could use `v2` tag as well 🤷

fix ci checkout action

---

.github/workflows/ci.yml

Do not run CI on commits/PRs unless at least 1 file is not documentation.
Given CI is a bit heavy this will save time waiting for small documentation changes and will save a bit of $$

do not run CI workflow on documentation changes

---

modules/cluster/README.md

This documentation caused some confusion for a user. Unlike the `system:masters` group which has cluster admin permissions from the `cluster-admin` ClusterRoleBinding,  `system:basic-user` is not a valid group without user-specified custom RBAC. `system:basic-user` is a ClusterRole with the following definition 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
annotations:
rbac.authorization.kubernetes.io/autoupdate: "true"
creationTimestamp: "2019-07-24T13:34:08Z"
labels:
kubernetes.io/bootstrapping: rbac-defaults
name: system:basic-user
resourceVersion: "68"
selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Abasic-user
uid: b6b451d4-ae17-11e9-997d-12781aca2b9a
rules:
- apiGroups:
- authorization.k8s.io
resources:
- selfsubjectaccessreviews
- …
```

rename example readonly group to avoid confusion

---

.github/workflows/release.yml
RELEASING.md

Closes #149 
Github action workflow for:
- Create github release
- Notify slack for successful releases
Manually triggered workflow .
There's a lot of scope to improve this process, left to a future issue - the release body is restricted to an input  on the workflow trigger which is quite small and only single-line:
It would be nice to automate the release body with a github action w/ CHANGELOG (or similar process).
Here's an example of the slack notification:

add release automation github action

---

test/cluster_test.go

Allow for expected kube-bench failures with bottlerocket
This should be fixed properly with https://github.com/aquasecurity/kube-bench/issues/808 and https://github.com/bottlerocket-os/bottlerocket/pull/1295
But, as these are known failures, this should not be a failure in our CI.
Workaround by patching kube-bench config for bottlerocket config paths, and allowing for a known number of failures.
connects #181
depends #178

Allow for expected kube-bench failures with bottlerocket

---

modules/iam/outputs.tf

The following error occurs while terraform plan is executed.
<details>
<summary>terraform plan</summary>
```
terraform plan
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
Error: Invalid depends_on reference
on .terraform/modules/eks_iam/modules/iam/outputs.tf line 7, in output "config":
7:     aws_iam_role_policy_attachment.eks_worker_node.policy_arn,
References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.
Error: Invalid depends_on reference
on .terraform/modules/eks_iam/modules/iam/outputs.tf line 8, in output "config":
8:     aws_iam_role_policy_attachment.eks_cni.policy_arn,
References in depends_on must be to a whole object (resource, etc), not to an
attribute of an object.
Error: …
```

[IAM module] Fix Invalid depends_on reference error

---

hack/generate_addons.sh
modules/cluster/addons/aws-ebs-csi-driver.yaml
modules/cluster/addons/aws-node-termination-handler.yaml
modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/kustomization.yaml

The terraform-aws-eks module uses several Docker images stored on Dockerhub but as the Dockerhub changed [its rate limit policy](https://www.docker.com/increase-rate-limits#:~:text=The%20rate%20limits%20of%20100,the%20six%20hour%20window%20elapses.), we have sometimes encountered the rate limit issue when we launch new containers.
This PR will change 
* the image repository for `aws-node-termination-handler` from Dockerhub to Amazon ECR
* the image repository for `aws-ebs-csi-driver` from Dockerhub to Google Container Registry.
I executed `hack/generate_addons.sh` after I changed the following files 📝 
* https://github.com/cookpad/terraform-aws-eks/compare/master...update_docker_image_to_use_public_ecr?expand=1#diff-7fb6b414f1d357d10100fb9e82f44f50d55e6e853060b8c554921a366b1220a2R4
* …

Use public ECR repository to bypass Dockerhub image rate limit

---

hack/generate_addons.sh
modules/cluster/addons/nvidia-device-plugin.yaml

To bypass the Dockerhub rate limits for the nvidia-device-plugin image, I'd like to use the public image registry which NVIDIA manages.
This PR also includes a [small change](https://github.com/cookpad/terraform-aws-eks/commit/38af30601b44f535da1be8f5a5dcc46902c2db9f) for `aws-ebs-csi-driver` which was generated by executing `hack/generate_addons.sh`.

[addons]  Use public NVIDIA image repository for nvidia-device-plugin

---

modules/cluster/addons/aws-ebs-csi-driver.yaml
modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/kustomization.yaml

continue from https://github.com/cookpad/terraform-aws-eks/pull/191#discussion_r577925761
* Override the image tag to use `v0.9.0` tag for aws-ebs-csi-driver image: https://github.com/cookpad/terraform-aws-eks/pull/196/files#diff-7fb6b414f1d357d10100fb9e82f44f50d55e6e853060b8c554921a366b1220a2R5-R7
Other changes are produced by `./hack/generate_addons.sh`.

[Addons] Use stable driver with v0.9.0

---

modules/cluster/addons/aws-k8s-cni.yaml

Update amazon-k8s-cni to 1.7.10.
This was missed in the 1.18 release so we should release a patch to previous releases as well as targetting 1.19.
Could help bug between `aws-node` / `kube-proxy` startup when a node comes online 
example from @dan-slinky-ckpd 
```
{"level":"info","ts":"2021-04-14T14:33:42.862Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2021-04-14T14:33:42.877Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2021-04-14T14:33:42.879Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
ERROR: logging before flag.Parse: E0414 14:34:12.902426      10 memcache.go:138] couldn't get current server API group list; will keep using cached value. (Get …
```

udpate aws-k8s-cni to 1.7.10

---

modules/cluster/addons/kube-proxy.yaml

Following the advice from https://github.com/aws/amazon-vpc-cni-k8s/issues/1078#issuecomment-804655593
This fix should stop us hitting the bug around unstable aws-node startup. 
I've made the bindAddress configurable via ipv4/6 usage as binding to 127.0.0.1 will not work for ipv6

bind kube-proxy to 127.0.0.1 when IPV6 is not required

---

modules/cluster/addons/aws-ebs-csi-driver.yaml
modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/daemonset_tolerations.yaml
modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/eks_iam_for_sa.yaml
modules/cluster/addons/kustomize/overlays/aws-ebs-csi-driver/kustomization.yaml

* Add the IAM role annotation back for the ebs-snapshot-controller ServiceAccount (removed in #213)
* Add NoSchedule toleration to ebs-csi-node DaemonSet so that it is scheduled to all nodes

Fix aws-ebs-csi driver issues

---

examples/cluster/gpu_node_group/main.tf
modules/cluster/addons/cluster-autoscaler.yaml
modules/cluster/addons/helm/cluster-autoscaler.yaml

Contributes #210
- increase memory/limit for cluster-autoscaler
- add p2.xlarge to example asg_node_group module example `gpu_node_group` 
Investigating CI failures on #225 I had a look at the test cluster, and the cluster-autoscaler pod was repeatedly restarting due to OOM errors.
The particular test failure was that the test workload pods wouldn't start in `validateClusterAutoscaler` (if the cluster-autoscaler pod was OOM then it would not be able to trigger scale-up).

Increase memory request and limit for cluster-autoscaler addon, add p2.large to gpu_node_group example

---

hack/roll_nodes.sh

When running `hack/roll_nodes.sh`, I got this warning message:
`Flag --delete-local-data has been deprecated, This option is deprecated
and will be deleted. Use --delete-emptydir-data.`
This change fixes that by using `--delete-emptydir-data` instead.
Reference: https://github.com/kubernetes/kubernetes/pull/95076

Deprecate --delete-local-data

---

UPGRADING.md

In this release we upgrade to aws-load-balancer-controller, but then
remove it.
As both actions happen within a single release, it's less confusing to
just say we removed it.

Simplify 1.19 upgrade notes

---

modules/cluster/kubectl/kubeconfig.yaml
modules/cluster/kubectl/main.tf
modules/cluster/kubectl/variables.tf

Passing the token from aws_eks_cluster_auth data source meant
that the token is generated at plan time - as the tokens
are only valid for 15 minutes this can cause issues when there
is some time elapsed between plan and apply, or if the apply takes
more than 15 minutes e.g. when provisioning a new cluster.
See also this documentation: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins

Switch kubectl to exec credential provider

---

.github/workflows/ci.yml
README.md
RELEASING.md
UPGRADING.md

Reference:
https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

Prepare repository for default branch rename

---

examples/cluster/gpu_node_group/main.tf

This should fix the flakiness we have seen with this test recently.
Using g4dn.xlarge instance type as this is currently the lowest cost
Nvidia GPU node

Run GPU node group tests with on_demand instances

---

test/cluster_test.go

Where we were cleaning up after tests by deleting all resources in a
manifest there could be some issues if the namespace gets deleted before
other resources.
e.g. https://github.com/cookpad/terraform-aws-eks/runs/3339274291?check_suite_focus=true
If we just delete the namespace then k8s will handle cleaning up all the
resources in the namespace.

Fix flaky tests

---

hack/roll_nodes.sh

Follow-up to f352e8a3246f5d87fc49a11cdcc06d0dc05d3984
`kubectl drain` accepts argument `--delete-emptydir-data` not `--delete-empty-dir`

fix hack/roll_nodes

---

examples/cluster/environment/main.tf
examples/cluster/environment/variables.tf
examples/vpc/main.tf
examples/vpc/variables.tf
main.tf
modules/vpc/subnets.tf
modules/vpc/variables.tf
modules/vpc/vpc.tf
variables.tf

* These tags were previously required by aws-load-balancer-controller/alb-ingress-controller
* We no longer ship an ingress controller with the module since #225
* aws-load-balancer-controller doesn't need those tags anyway since v2.1.2 - https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1773

Remove cluster-name tagging from subnets

---

test/cluster_test.go

We should check that the cluster autoscaler actually scales up the
cluster - not just that we have a node count of 2 (we might not have
started from 1).

Fix testing that autoscaler scales up the cluster

---

.github/workflows/ci.yml
README.md
examples/cluster/bottlerocket_node_group/main.tf
examples/cluster/environment/main.tf
examples/cluster/gpu_node_group/main.tf
examples/cluster/main.tf
examples/cluster/standard_node_group/main.tf
examples/vpc/main.tf
modules/asg_node_group/providers.tf
modules/cluster/providers.tf
modules/iam/providers.tf
modules/vpc/providers.tf
versions.tf

Since #240 we require secret encrytion on all clusters. Users hit this bug after enabling secret encryption hashicorp/terraform-provider-aws#19986 unless using aws provider >=3.49.0
NB: for the 1.20 release this will be superseded by #261, but intending to patch this to 1.19.2 for users using https://github.com/cookpad/terraform-aws-eks/pull/240 in 1.19.1 as they will hit 🐛  hashicorp/terraform-provider-aws#19986

require aws provider version >= 3.49.0

---

main.tf
variables.tf

The root module is not intended for production use. To make it easy for users to get started, using endpoint_public_access=true allows users to get started without configuring any custom networking to access the EKS api.
Closes #251 
@aidy as discussed - this updates the root module to default to
```
endpoint_public_access       = true
endpoint_public_access_cidrs = ["0.0.0.0/0"]
```
in the cluster module. This is against the recommended pattern introduced in #240, but to close #251 we want to provide configuration that works easily for the user. From 1.20 we will remove the root module, so this is intended only for patching 1.19
NB: we don't run any CI steps against the root module, but validating:
```
$ terraform validate …
```

Use endpoint_public_access=true for root module

---

hack/kubeconfig.sh
modules/asg_node_group/main.tf
modules/asg_node_group/variables.tf
modules/cluster/addons.tf
modules/cluster/variables.tf

Fixes #308
My approach here was to remove a feature to make implementation much simpler - so we will need to update this in the UPGRADING document as a breaking change.

Remove template provider

---

modules/cluster/kubectl/kubeconfig.yaml

Currently, when you try to do `terraform apply` on the machine with `kubectl` version 1.24+, you will run into this error:
```
╷
│ Error: local-exec provisioner error
│ 
│   with module.staging-eks-cluster.module.nvidia_device_plugin.null_resource.apply[0],
│   on .terraform/modules/staging-eks-cluster/modules/cluster/kubectl/main.tf line 37, in resource "null_resource" "apply":
│   37:   provisioner "local-exec" {
│ 
│ Error running command 'echo "$KUBECONFIG" > .terraform/modules/staging-eks-cluster/modules/cluster/kubectl/045cff270a0a0c5ff6c5dc81689cc1b02625724a.kubeconfig
│ 
│ echo "$MANIFEST" | kubectl --kubeconfig=.terraform/modules/staging-eks-cluster/modules/cluster/kubectl/045cff270a0a0c5ff6c5dc81689cc1b02625724a.kubeconfig apply -f - || echo "$MANIFEST" | kubectl
│ …
```

Update kubeconfig to use client.authentication.k8s.io/v1beta1

---

UPGRADING.md
examples/cluster/main.tf
modules/cluster/addons.tf
modules/cluster/providers.tf
modules/cluster/variables.tf

This PR exposes addon [`configuration_values`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#configuration_values) in the cluster module's variables.
This will allow users to configure addons (for example, increasing no. of CoreDNS replicas).
This change can also be cherry-picked onto the 1.22 release branch, but we will need to upgrade the `aws-ebs-csi-driver` addon on that branch to `v1.10.0-eksbuild.1` to support configuration values.

Support custom configuration values for addons

---

modules/cluster/addons/cluster-autoscaler.yaml
modules/cluster/addons/helm/cluster-autoscaler.yaml

https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

Migrate k8s.gcr.io to registry.k8s.io

---

modules/cluster/aws_ebs_csi_driver_iam.tf
modules/cluster/cluster_autoscaler_iam.tf
modules/cluster/kubectl/command.sh
modules/cluster/kubectl/main.tf
modules/cluster/main.tf
modules/cluster/variables.tf

📝 These are some enhancements we have been using on the web platform clusters for some time!
It would be great to merge them in so we can use the mainline release!
* Removes the provisioner that "waits" for the cluster to be ready, and instead adding a similar check to the kubectl command fixes a lot of errors that can require a re-run when provisioning a cluster.
* In our environment we need to give all our IAM roles a specific prefix - this change (optionally) allows this to be done!

Enhancements from web-platform

---

examples/cluster/main.tf
main.tf
modules/karpenter/README.md
modules/karpenter/controller_iam.tf
modules/karpenter/data.tf
modules/karpenter/fargate.tf
modules/karpenter/interruption_queue.tf
modules/karpenter/node_iam.tf
modules/karpenter/outputs.tf
modules/karpenter/variables.tf
modules/karpenter/versions.tf
outputs.tf
variables.tf

It seemed a bit weird that we did a lot of work to remove all of the non-core functions from the module, just to add the support for karpenter as a core part of the module.
Moving support for Karpenter to a submodule doesn't make configuring a cluster much more dificult, but does reduce the complexity of the core module, and hopefully should make ongoing maintince a little simpler.  Especially if we decided to use some other node provisioning tool in the future.

Seperate karpenter config to a submodule

---

modules/karpenter/controller_iam.tf
modules/karpenter/data.tf
modules/karpenter/interruption_queue.tf

This updates the karpenter controller IAM policy inline with the upstream documentation/cloudformation
https://github.com/aws/karpenter/blob/27ad171092b9d448f7ed8f0f6fc9754419d3c12d/website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml#L37-L212
The advantage of this policy is that more resources are scoped, so the chance of unxpected opperation impacting other resources e.g. (from another cluster) is reduced.

Update karpenter IAM policy

---

modules/karpenter/controller_iam.tf
modules/karpenter/variables.tf

This may be needed for migration, if for example karpenter is already managing nodes with a different node role arn, so that it can continue to manage existing nodes until they are replaced.

Allow additional_node_role_arns to be specified on karpenter

---

modules/karpenter/controller_iam.tf
modules/karpenter/interruption_queue.tf
modules/karpenter/node_iam.tf
modules/karpenter/variables.tf
test/cluster_test.go

Karpenter 0.32 introduces new v1beta apis and depricates the existing v1alpha apis.
🔗 https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#upgrade-procedure
These APIs require a different IAM policy for the controler to work.
This PR adds 2 new variables to the karpenter module.
`v1alpha` and `v1beta` which will allow one or both policies to be used (useful during the migration process)
We will enable both policies by default in the 1.28 release, then drop support for the `v1alpha` policy in 1.30 (as karpenter 1.31 doesn't work properly with k8s 1.30).

Support karpenter 0.32+

---

modules/karpenter/controller_iam.tf
modules/karpenter/variables.tf
outputs.tf
test/cluster_test.go
variables.tf

This PR attaches a controller policy for Karpenter v1 in the karpenter module. The policy content is taken from https://github.com/aws/karpenter-provider-aws/blob/v1.0.6/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml. I've added module variables `v1` and `v1beta` to help migration as you did in https://github.com/cookpad/terraform-aws-eks/pull/368.
- policy JSON diff extracted from the cloudformation.yaml: https://gist.github.com/coord-e/04ad1c4bc54b60899e7b4f2b33bf07dd#file-policies-diff
- policy document Terraform diff extracted from this PR: https://gist.github.com/coord-e/04ad1c4bc54b60899e7b4f2b33bf07dd#file-documents-diff
I'll make a PR to backport this to v0.29 and v0.30 after this is merged.

Enable to use Karpenter v1 controller policy

---

CODEOWNERS

Currently this repository specifies @cookpad/web-platform-team as a code owner. The team is merged into @cookpad/platform-task-force, so the code owner should be @cookpad/platform-task-force.

Specify @cookpad/platform-task-force as a code owner

---

modules/karpenter/controller_iam.tf

follow-up of #371 
In #371, I separated Karpenter v1beta and v1 policies to their own managed policies. However I noticed that when we apply this change, the destruction of `aws_iam_role_policy` and creation of `aws_iam_role_attachment` can happen in any order, possibly result in a moment that no policy is attached to the role... it's sufficient to make only v1 a managed policy to address the original issue, so I revert the v1beta policy back to an inline policy in this PR to prevent the kind of disruption mentioned above.

Use inline policy for v1beta to avoid resource recreation

---

modules/karpenter/controller_iam.tf
modules/karpenter/variables.tf
outputs.tf
variables.tf

This PR backports changes from https://github.com/cookpad/terraform-aws-eks/pull/371 and https://github.com/cookpad/terraform-aws-eks/pull/372 into the 1.29 release branch.

Enable to use Karpenter v1 controller policy (backport to 1.29)

---

modules/karpenter/controller_iam.tf
modules/karpenter/variables.tf
outputs.tf
test/cluster_test.go
variables.tf

This PR backports changes from https://github.com/cookpad/terraform-aws-eks/pull/371 and https://github.com/cookpad/terraform-aws-eks/pull/372 into the 1.30 release branch.

Enable to use Karpenter v1 controller policy (backport to 1.30)

---

cluster_iam.tf
examples/cluster/.terraform.lock.hcl

Fixes this warning:
```
│ Warning: Argument is deprecated
│
│   with module.cluster.aws_iam_role.eks_cluster_role,
│   on .terraform/modules/cluster/cluster_iam.tf line 5, in resource "aws_iam_role" "eks_cluster_role":
│    5: resource "aws_iam_role" "eks_cluster_role" {
│
│ The inline_policy argument is deprecated. Use the aws_iam_role_policy resource instead. If Terraform should exclusively manage all inline policy associations (the current behavior of
│ this argument), use the aws_iam_role_policies_exclusive resource as well.
```

Fix inline policy deprecation
